### ISSUE TITLE
Getting an Error for Invalid Subscription Requests

### ISSUE THREAD

**Issue by Nuvindu** [graphql/graphiql#2534]
I'm currently working on integrating GraphQL subscriptions in Ballerina language to a GraphiQL web based client. It uses websockets for subscriptions and works fine with valid subscription requests. 
But for invalid subscription requests, an error occurs like this.
![image](https://user-images.githubusercontent.com/63797478/177081309-cae127f3-0816-4833-a1de-dab582714f3a.png)

The GraphiQL client receives this websocket payload.
```
{"type":"error", "id":"b2dd2712-1ac5-48fa-9f25-8b88d3d80bf0", "payload":{"errors":[{"message":"Cannot query field \"messag\" on type \"MsgType\".", "locations":[{"line":4, "column":5}]}]}}
```

**Comment by Nuvindu** [comment]
I removed `errors` field in the WebSocket payload and tried again. 
```
{"type":"error", "id":"a2598b2a-ba44-4bee-be9a-40eea8e5cc4e", "payload":[{"message":"Cannot query field \"messag\" on type \"MsgType\".", "locations":[{"line":4, "column":5}]}]}
```
Then only the `message` field is correctly shown. But still an error occurrs.
![subscription-graphiql-error](https://user-images.githubusercontent.com/63797478/177082351-10da0287-2e5a-4c34-9e57-2a9df27a9dc0.png)

In the console, the error is displayed as follows.
```
lib.ts:128 Uncaught (in promise) Error: Cannot query field "messag" on type "MsgType".
    at Object.error (lib.ts:128:13)
    at Object.a2598b2a-ba44-4bee-be9a-40eea8e5cc4e (graphql-ws.js:526:46)
    at emit (graphql-ws.js:249:98)
    at Object.emit (graphql-ws.js:276:25)
    at o.onmessage (graphql-ws.js:363:33)
```

**Comment by thomasheyenbrock** [comment]
Thanks for reporting @Nuvindu! I thought this would be a regression with the recent refactorings we did, but seems like this has been an issue even before that. I opened a PR that would fix this.

**Comment by Nuvindu** [comment]
@thomasheyenbrock Is there any update for this?

**Comment by thomasheyenbrock** [comment]
@Nuvindu thanks for following up! I have been busy the last weeks focussing on getting the new design ready, so this fell kinda off the plate 😞  I'll try to follow up this or next week 🤞

**Comment by Nuvindu** [comment]
No worries!🙌. I saw the pr is almost completed. That's why I asked.

**Comment by thomasheyenbrock** [comment]
This should now be fixed in `graphiql@1.11.1`

**Comment by DimuthuMadushan** [comment]
@thomasheyenbrock It seems like this issue is still there in the GraphiQL new version. 
![Screenshot from 2022-10-19 12-01-36](https://user-images.githubusercontent.com/35717653/196614550-41d03a77-ddaf-4f30-bfc2-751d8f6fe374.png)

Websocket payload: 
```shell
{"type":"error", "id":"3d7489ca-87e0-4d88-9087-e3ce1f5953d8", "payload":{"errors":[{"message":"Cannot query field \"donate\" on type \"Subscription\".", "locations":[{"line":2, "column":3}]}]}}
```
