### ISSUE TITLE
GraphQL Explorer Plugin throwing error

### ISSUE THREAD

**Issue by faizan-siddiqui** [graphql/graphiql#2763]
I have added GraphQL Explorer Plugin, following the same steps in the readme here and the examples: https://github.com/graphql/graphiql/tree/main/packages/graphiql-plugin-explorer

The plugin button shows up but when i click it, i get this error:
`'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
`

Is there anything I'm missing, has anyone else come across this?

**Comment by thomasheyenbrock** [comment]
Hey @faizan-siddiqui 👋 thanks for opening an issue! Can you give more context about the setup you're using? I copy-pasted the example from the readme into a Codesandbox but wasn't able to reproduce the issue: https://codesandbox.io/s/agitated-wright-m56pb2?file=/src/App.tsx

**Comment by tom-quiltt** [comment]
I have the same problem and I am using Next.js.

**Comment by jonathanawesome** [comment]
@tom-quiltt @faizan-siddiqui additional information about your setup or, even better, a running example would help with troubleshooting.

**Comment by AndKiel** [comment]
In my remix, when I try to upgrade graphiql to v2 and use the explorer plugin, I get the following error/stack after clicking the button to open explorer:

```
useGivenContext@http://localhost:3000/build/_shared/chunk-6QWELR4S.js:675:60
ExplorerPlugin@http://localhost:3000/build/routes/explorer-GBKJ37U4.js:15383:23
renderWithHooks@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:13563:35
mountIndeterminateComponent@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:16292:21
beginWork@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:17247:22
beginWork$1@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:21048:22
performUnitOfWork@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:20496:20
workLoopSync@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:20432:30
renderRootSync@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:20411:15
recoverFromConcurrentError@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:20033:42
performSyncWorkOnRoot@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:20175:28
flushSyncCallbacks@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:10576:30
node_modules/react-dom/cjs/react-dom.development.js/ensureRootIsScheduled/<@http://localhost:3000/build/_shared/chunk-XVUW4YK6.js:19924:21
```

I just did it now so I haven't investigated enough yet. If I have something more, I'll add info to this comment.

**Comment by wilhelmeek** [comment]
Fix for me was to make sure my versions of `@graphiql/react` and `@graphiql/toolkit` were in sync.

**Comment by AndKiel** [comment]
@wilhelmeek, thank you. For some unknown reason, I had `@graphiql/react` 1.0.0-next.2 in my package.json. Using the latest 0.x version fixed the crash for me too. No idea how it got there. 🤦🏻‍♂️ 

Now I only have to come up with why is my implementation broken when writing query (caret going back to the beginning).

**Comment by thomasheyenbrock** [comment]
Good shout @wilhelmeek! @faizan-siddiqui can you check which version of `@graphiql/react` you have installed?

**Comment by AndKiel** [comment]
My other issue was resolved by rewriting components to use `GraphiQLProvider` + `GraphiQLInterface` with `useEditorContext`. My mistake was trying to keep my own state management instead of relying on your context and query/variable editor.

**Comment by faizan-siddiqui** [comment]
I added `"@graphiql/react": "^0.13.2"` and `"@graphiql/toolkit": "^0.8.0"` to my dependencies in `package.json` and still get the same error :(

**Comment by faizan-siddiqui** [comment]
Full stack trace is
```
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at useEditorContext (bundle.js:24224)
    at ExplorerPlugin (bundle.js:22963)
    at renderWithHooks (bundle.js:113030)
    at mountIndeterminateComponent (bundle.js:116695)
    at beginWork (bundle.js:118163)
    at HTMLUnknownElement.callCallback (bundle.js:100826)
    at Object.invokeGuardedCallbackDev (bundle.js:100875)
    at invokeGuardedCallback (bundle.js:100937)
    at beginWork$1 (bundle.js:123950)
    at performUnitOfWork (bundle.js:123083)
```

**Comment by thomasheyenbrock** [comment]
@faizan-siddiqui can you share a snippet of your React code and details about the setup (Next.js, Vite, CRA, whatever you're using) so that we can dig into this?

**Comment by faizan-siddiqui** [comment]
Hi @thomasheyenbrock thanks for having a look, yep i was able to replicate the problem here, I suspect it's something in my `package.json` that is conflicting, as I used almost the same sandbox as the one you linked but put in the dependencies I am using https://codesandbox.io/s/little-bird-23lulc

**Comment by faizan-siddiqui** [comment]
looks like i found the problem, I was using `"graphiql": "2.0.3"`, I changed it to `"graphiql": "2.0.7"` and it's working now, I tested removing  "@graphiql/react": "^0.13.2" and "@graphiql/toolkit": "^0.8.0" and it's still working now , thanks heaps everyone!

**Comment by faizan-siddiqui** [comment]
Seems to work for me now, the issue was I was using `"graphiql": "2.0.3"` instead of `"graphiql": "2.0.7"`

**Comment by eMerzh** [comment]
hey i got the same issue with graphiql 2.2.0....
if you https://codesandbox.io/s/agitated-wright-m56pb2?file=/package.json and change graphiql to 2.2.0, then click on explorer icon you'll have 
 
<img width="892" alt="Screenshot 2022-12-01 at 09 10 18" src="https://user-images.githubusercontent.com/177003/204999735-0058b4b8-122f-4bf0-b266-419bc74cd824.png">

**Comment by thomasheyenbrock** [comment]
@eMerzh if you also upgrade `@graphiql/plugin-explorer` to the latest version (which is `0.1.12`) then it should work

**Comment by hugh-onf** [comment]
Hey, so it happens again on latest `0.1.20` but basically ALL versions after/except the `0.1.12` as @thomasheyenbrock has mentioned above, are having the same issues.
For the context, I am running this inside a Storybook but the error is the same as everyone else.
Thanks.

**Comment by thomasheyenbrock** [comment]
@hugh-onf can you share a reproduction? Are you using the latest versions of all GraphiQL related packages?

**Comment by hugh-onf** [comment]
@thomasheyenbrock thanks and indeed I was using an older `graphiql@2.2.0` but after updating it to the latest `2.4.7` it seems all working together now.
