### ISSUE TITLE
[vscode-graphql] 🐞 VSCode extension version v0.7.6 fails to start

### ISSUE THREAD

**Issue by MartinSoto** [graphql/graphiql#2801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```Markdown
The VSCode extension (id GraphQL.vscode-graphql) simply fails to start. I tried uninstalling and installing it anew and found the lines listed below in the log.

I'm using a multi-root workspace setup. Only one of the projects in the workspace contains a configuration, which is placed at the project root.


[2022-10-10 18:06:14.888] [exthost] [info] ExtensionService#_doActivateExtension GraphQL.vscode-graphql-execution, startup: false, activationEvent: 'workspaceContains:**/.graphqlrc,**/.graphqlrc.{json,yaml,yml,js,ts,toml},**/graphql.config.{json,yaml,yml,js,ts,toml},**/package.json', root cause: GraphQL.vscode-graphql
[2022-10-10 18:06:14.892] [exthost] [error] Activating extension GraphQL.vscode-graphql-execution failed due to an error:
[2022-10-10 18:06:14.892] [exthost] [error] Error: Cannot find module 'escape-html'
Require stack:
- /root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.0/dist/providers/exec-content.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.0/dist/extension.js
- /vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/loader.js
- /vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/bootstrap-amd.js
- /vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
	at Function.Module._load (node:internal/modules/cjs/loader:778:27)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.0/dist/providers/exec-content.js:8:39)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.0/dist/extension.js:5:24)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/loader.js:5:101)
	at p._loadCommonJSModule (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:66574)
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
```
```


### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```Markdown
- LSP Server Version: 0.7.6
- OS: Windows with Linux container
- LSP Client:
```

**Comment by acao** [comment]
linked to #2800, seems to be a bundling bug. everything works fine in the local setup, but there is an extension bundling issue again

**Comment by acao** [comment]
seems to be an issue with `vsce package --yarn`

**Comment by acao** [comment]
![image](https://user-images.githubusercontent.com/1368727/194934410-46d29bee-b335-4855-a7ab-c972718c17ab.png)

**Comment by acao** [comment]
@MartinSoto 0.7.7 should be the one! there is no actual change to `vscode-graphql` but to `vscode-graphql-execution` which also gets a new patch version. the `vsce` cli used to package extensions needed an updated, and the `--yarn` flag failed, causing dependencies to go missing with this new extension built around re-added functionality. enjoy the fix!

**Comment by jeanbenitezu** [comment]
Hey @acao, thanks for helping to fix this issue.
I'm getting an error in v0.7.7 (see image) but, honestly, I don't know how to get that output @MartinSoto has. By moving to v0.7.5 it is working again, so I guess it is the same issue.
![image](https://user-images.githubusercontent.com/82394571/194955919-477041fd-cc3d-4fd4-ab6f-683398e16365.png)

**Comment by acao** [comment]
@jeanbenitezu try 0.7.7 and the latest `graphql.vscode-graphql-execution` extension, there were a few more issues, all should be working now

**Comment by MartinSoto** [comment]
Hi @acao! 0.7.8 isn't working for me either:

```
[2022-10-10 23:51:33.118] [exthost] [info] ExtensionService#_doActivateExtension GraphQL.vscode-graphql-execution, startup: false, activationEvent: 'workspaceContains:**/.graphqlrc,**/.graphqlrc.{json,yaml,yml,js,ts,toml},**/graphql.config.{json,yaml,yml,js,ts,toml},**/package.json', root cause: GraphQL.vscode-graphql
[2022-10-10 23:51:33.126] [exthost] [error] Activating extension GraphQL.vscode-graphql-execution failed due to an error:
[2022-10-10 23:51:33.126] [exthost] [error] Error: Cannot find module 'brace-expansion'
Require stack:
- /root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/node_modules/minimatch/minimatch.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/node_modules/graphql-config/index.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/dist/providers/exec-content.js
- /root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/dist/extension.js
- /vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/loader.js
- /vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/bootstrap-amd.js
- /vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/bootstrap-fork.js
	at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
	at Function.Module._load (node:internal/modules/cjs/loader:778:27)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/node_modules/minimatch/minimatch.js:21:16)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/node_modules/graphql-config/index.js:8:35)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/dist/providers/exec-content.js:5:26)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Object.<anonymous> (/root/.vscode-server/extensions/graphql.vscode-graphql-execution-0.1.3/dist/extension.js:5:24)
	at Module._compile (node:internal/modules/cjs/loader:1103:14)
	at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
	at Module.load (node:internal/modules/cjs/loader:981:32)
	at Function.Module._load (node:internal/modules/cjs/loader:822:12)
	at Function.r._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:116:14565)
	at Function.v._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:65015)
	at Function.E._load (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:64383)
	at Module.require (node:internal/modules/cjs/loader:1005:19)
	at require (node:internal/modules/cjs/helpers:102:18)
	at Function.r [as __$__nodeRequire] (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/loader.js:5:101)
	at p._loadCommonJSModule (/vscode/vscode-server/bin/linux-x64/64bbfbf67ada9953918d72e1df2f4d8e537d340e/out/vs/workbench/api/node/extensionHostProcess.js:111:66574)
	at processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async Promise.all (index 0)
```

The way it looks, something is still missing.

By the way @jeanbenitezu, I see the output only if I uninstall the extension and reinstall it right away. Otherwise there's no error output whatsoever.

**Comment by jeanbenitezu** [comment]
confirmed, still getting the same errors with both extension updated

**Comment by acao** [comment]
ok, well i'm going to just disable the exec extension for now

**Comment by acao** [comment]
ok, cutting a new release of `GraphQL.vscode-graphql@0.7.8` which removes `GraphQL.vscode-graphql-execution` until we address these bundling woes completely. Apologies for the hiccup everyone. Enjoy multi-root workspaces and other optimizations!

**Comment by acao** [comment]
`GraphQL.vscode-graphql@0.7.10` is the fix version [as confirmed in discord](https://discord.com/channels/625400653321076807/863688262181453845/1029194541577801739). thanks everyone!

**Comment by MartinSoto** [comment]
Works for me as well, thanks a lot for the quick reaction!
